apiVersion: v1
kind: Secret
metadata:
  name: poseidon-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdFVzZXI= # base64 'rootUser'
  MONGO_INITDB_ROOT_PASSWORD: c3Ryb25nUGFzc3dvcmQ= # base64 'strongPassword'
  JWT_KEY: VGhpc0lzQVNlY3JldEtleVdpdGhBdExlYXN0MzJDaGFyYWN0ZXJz # base64 'ThisIsASecretKeyWithAtLeast32Characters'
  JWT_ISSUER: UG9zZWlkb25BUEk= # base64 'PoseidonAPI'
  JWT_AUDIENCE: UG9zZWlkb25DbGllbnQ= # base64 'PoseidonClient'
  DATABASE_CONFIG_CONNECTIONSTRING: bW9uZ29kYjovL3Jvb3RVc2VyOnN0cm9uZ1Bhc3N3b3JkQHBvc2VpZG9uLW1vbmdvZGIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9Qb3NlaWRvbkRCP2F1dGhTb3VyY2U9YWRtaW4= # base64 of 'mongodb://rootUser:strongPassword@poseidon-mongodb.default.svc.cluster.local:27017/PoseidonDB?authSource=admin'
