version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: poseidon_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      ENVIRONMENT: docker-compose
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: "mongosh --eval 'db.adminCommand(\"ping\")'"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - poseidon-net

  poseidon-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      MONGO_CONNECTION_STRING: >
        mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    depends_on:
      - mongodb
    networks:
      - poseidon-net

  mongodb-seeder:
    image: mongo:latest
    container_name: mongo-seeder
    depends_on:
      - mongodb
    volumes:
      - ./Mongo-seed:/mongo-seed
    entrypoint: ["/bin/bash", "/mongo-seed/init-mongo.sh"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      ENVIRONMENT: docker-compose  # <-- Add this line
    networks:
      - poseidon-net
    restart: "no"

networks:
  poseidon-net:
