version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: poseidon_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      ENVIRONMENT: docker-compose
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - poseidon-net

  poseidon-service:  # Renamed from poseidon-api to poseidon-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poseidon_service  # Optional: For clarity
    ports:
      - "9090:8080"  # Host port 9090 maps to container port 8080
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      DatabaseConfig__ConnectionStringDocker: ${DatabaseConfig__ConnectionStringDocker}
      DatabaseConfig__DatabaseName: ${DatabaseConfig__DatabaseName}
      Jwt__Key: ${Jwt__Key}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}
    depends_on:
      - mongodb
    networks:
      - poseidon-net

  poseidon-frontend:
    image: cheloghm/poseidon-frontend:latest
    container_name: poseidon_frontend
    ports:
      - "3000:80"  # Serve frontend on port 3000
    networks:
      - poseidon-net
    depends_on:
      - poseidon-service  # Updated dependency
    environment:
      - API_SERVICE=poseidon-service
      - API_PORT=8080

  mongodb-seeder:
    image: mongo:latest
    container_name: mongo-seeder
    depends_on:
      - mongodb
    volumes:
      - ./Mongo-seed:/mongo-seed
    entrypoint: ["/bin/bash", "/mongo-seed/init-mongo.sh"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      ENVIRONMENT: docker-compose
    networks:
      - poseidon-net
    restart: "no"

networks:
  poseidon-net:
