# sre-security/rbac/rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: poseidon-demo
  name: poseidon-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poseidon-rolebinding
  namespace: poseidon-demo
subjects:
  - kind: ServiceAccount
    name: default
    namespace: poseidon-demo
roleRef:
  kind: Role
  name: poseidon-role
  apiGroup: rbac.authorization.k8s.io
