apiVersion: apps/v1
kind: Deployment
metadata:
  name: poseidon-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poseidon
  template:
    metadata:
      labels:
        app: poseidon
    spec:
      containers:
      - name: poseidon
        image: your-docker-image
        ports:
        - containerPort: 80
  