# helm/backend/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "poseidon-backend.fullname" . }}
  labels:
    {{- include "poseidon-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "poseidon-backend.name" . }}
