apiVersion: v1
kind: ConfigMap
metadata:
  name: poseidon-logstash-config
  namespace: logging
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      # Add any necessary filters here
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch.logging.svc.cluster.local:9200"]
        index => "poseidon-%{+YYYY.MM.dd}"
      }
    }
