apiVersion: v1
kind: Service
metadata:
  name: poseidon-api
  labels:
    app: poseidon
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Using Network Load Balancer
spec:
  selector:
    app: poseidon
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8081
  type: LoadBalancer
