apiVersion: apps/v1
kind: Deployment
metadata:
  name: poseidon-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poseidon-mongodb
  template:
    metadata:
      labels:
        app: poseidon-mongodb
    spec:
      containers:
        - name: mongodb
          image: cheloghm/poseidon-mongodb-seed:1.6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: poseidon-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poseidon-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: poseidon-config
                  key: MONGO_DB_NAME
