---
apiVersion: v1
kind: Service
metadata:
  name: poseidon-service
spec:
  selector:
    app: poseidon
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8081
  type: LoadBalancer