---
name: "CI/CD Pipeline"

on:
  pull_request:
    branches:
      - "main"
      - "dev"
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/poseidon-api:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/poseidon-api:${{ github.sha }}

      - name: Save Docker Image Tag
        id: docker_tag
        run: echo "tag=${{ github.sha }}" >> $GITHUB_ENV

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run Unit Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/poseidon-api:${{ env.tag }} \
          dotnet test /src/Poseidon.Tests/Poseidon.Tests.csproj --no-build

  lint:
    name: Lint and Code Quality Check
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linter
        run: |
          sudo apt-get install -y dotnet-format

      - name: Run Lint Check
        run: |
          dotnet format --check

  security_scan:
    name: Run Security Scan
    runs-on: ubuntu-latest
    needs: test
    container:
      image: aquasec/trivy:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run vulnerability scan
        run: |
          trivy image --severity CRITICAL --exit-code 1 \
          ${{ secrets.DOCKER_HUB_USERNAME }}/poseidon-api:${{ env.tag }}

  deploy_dev:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Kubernetes (Dev)
        run: |
          kubectl apply -f k8s/Deployment.yml
          kubectl apply -f k8s/Service.yml

  manual_approval:
    name: Manual Approval for Production
    runs-on: ubuntu-latest
    needs: deploy_dev
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Await Approval
        run: |
          echo "Approve this deployment to Prod?"

  deploy_prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: manual_approval
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Kubernetes (Prod)
        run: |
          kubectl apply -f k8s/Deployment.yml
          kubectl apply -f k8s/Service.yml
