# sre-security/kibana/values.yaml

replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: 7.10.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5601

env:
  ELASTICSEARCH_URL: "http://poseidon-elasticsearch:9200"
