# sre-security/logstash/values.yaml

replicaCount: 1

image:
  repository: docker.elastic.co/logstash/logstash
  tag: 7.10.0
  pullPolicy: IfNotPresent

logstashConfig: |
  input {
    http {
      port => 5000
      codec => json
      # Optional: SSL and authentication configurations
    }
  }

  filter {
    mutate {
      add_field => { "source" => "frontend" }
    }
  }

  output {
    elasticsearch {
      hosts => ["http://poseidon-elasticsearch:9200"]
      index => "poseidon-frontend-logs-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "changeme" # Use Kubernetes Secrets for sensitive data
    }
  }

service:
  type: ClusterIP
  port: 5000
